modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="stackedblockssupplementaries"
version="25.05.06-1.19-forge"
displayName="Stacked Blocks: Supplementaries"
authors="Axperty"
description="A mod that adds compatibility between Stacked Blocks and Supplementaries."
logoFile="assets/stackedblockssupplementaries/logo.png"

[[dependencies.stackedblockssupplementaries]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.stackedblockssupplementaries]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.stackedblockssupplementaries]]
modId="stackedblocks"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.stackedblockssupplementaries]]
modId="supplementaries"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"
